#!/usr/bin/env node
// Generate a small env.js file for the frontend with API URL and other public config
// Usage: This runs in Netlify build. Provide API_BASE_URL or BACKEND_URL as env vars.

const fs = require('fs');
const path = require('path');

try {
  const apiBase = process.env.API_BASE_URL || process.env.BACKEND_URL || '';
  const targetDir = path.join(__dirname, '..', 'quetzal-platform', 'fronted', 'public', 'js');
  const targetFile = path.join(targetDir, 'env.js');

  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  const content = `// Auto-generated by build\nwindow.API_BASE_URL = ${JSON.stringify(apiBase)};\n`;
  fs.writeFileSync(targetFile, content, 'utf8');

  console.log(`Wrote env.js with API_BASE_URL='${apiBase}' to ${targetFile}`);
} catch (err) {
  console.error('Failed to generate env.js:', err.message);
  process.exit(1);
}
